spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        ejb:
          event:
            load: uz.dev.caveatemptor.repository.listener.CustomLoadEventListener
        jdbc:
          batch_size: 100
#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: trace

---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      persistence:
        schema-generation:
      #            create-source: script-then-metadata
      #            drop-source: metadata-then-script
      #            create-script-source: complexSchemas/CreateScript.sql
      #            drop-script-source: complexSchemas/DropScript.sql
      #          sql-load-script-source: complexSchemas/LoadScript.sql
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

---

spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/db_caveatemptor"
    username: "user"
    password: "12345678"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---

spring:
  profiles: cache
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        javax:
          cache:
            missing_cache_strategy: create
      net:
        sf:
          ehcache:
            configurationResourceName: /cache/ehcache.xml